# Configuration file for the image processing service

allowed_hosts:
  - "sub.example1.com"
  - "sub.example2.net"

# WebP Image Processing Settings
webp:
  quality: 75          # Quality of the converted images (0-100)
  lossless: false      # Toggle lossless compression
  near_lossless: 80    # Near lossless compression setting (0-100)

# Caching Settings
cache:
  expiration_minutes: 60            # Cache expiration time in minutes
  cleanup_interval_minutes: 120     # Cache cleanup interval in minutes
  cache_enabled: false
  nocache_header: "X-No-Cache" # You can change the header name as needed

# Concurrency Settings
concurrency:
  max_goroutines: 10                # Maximum number of goroutines
  request_timeout_seconds: 30       # Request timeout in seconds

# HTTP Client Settings
http_client:
  timeout_seconds: 10               # HTTP client timeout in seconds

