# Configuration file for the image processing service

allowed_hosts:
  - "pelikan.media"
  - "cdn.mahshow.com"

# WebP Image Processing Settings
webp:
  quality: 75          # Quality of the converted images (0-100)
  lossless: false      # Toggle lossless compression
  near_lossless: 80    # Near lossless compression setting (0-100)

# Caching Settings
cache:
  expiration_minutes: 60            # Cache expiration time in minutes
  cleanup_interval_minutes: 120     # Cache cleanup interval in minutes
  cache_enabled: false
  nocache_header: "X-No-Cache" # You can change the header name as needed

# Concurrency Settings
concurrency:
  max_goroutines: 500                # Maximum number of goroutines

# HTTP Client Settings
http_client:
  timeout_seconds: 40               # HTTP client timeout in seconds
  dial_timeout_seconds: 5               # HTTP client timeout in seconds
  keep_alive: 30
  TLS_handshake_timeout: 10
  response_header_timeout: 30
  expect_continue_timeout: 1
  idle_conn_timeout: 90
