services:
  image_processing:
    image: ghcr.io/mohammad362/ngax/ngax:latest
    container_name: image_processing
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9080:9080"
    restart: on-failure
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "1"
