version: '3.8'

services:
  image_processing:
    image: ghcr.io/mohammad362/ngax/ngax
    container_name: image_processing
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    restart: on-failure
    volumes:
      - ./config.yaml:/app/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "1"
        

